#!/usr/bin/env python2
# -*- coding: utf-8 -*-
"""
Created on Thu Nov 15 16:09:51 2018

@author: jessicahummel
"""

import pandas
import scipy
import scipy.integrate as spint
from plotnine import *

params=(1,10)
y=[1]
times=range(0,100)
     
def coexistSim(y,t0,R1,a11,a12,R2,a22,a21):
    N1=y[0]
    N2=y[1]
    
    dN1dt=R1*(1-N1*a11-N2*a12)*N1
    dN2dt=R2*(1-N2*a22-N1*a21)*N2
    
    return [dN1dt,dN2dt]

#a12<a11 and a21<a22
    
#case1
times=range(0,100)
y0=[1,1]
params=(0.5,0.003,0.01,0.5,0.003,0.01)

sim=spint.odeint(func=coexistSim,y0=y0,t=times,args=params)
simDF=pandas.DataFrame({"t":times,"species1":sim[:,0],"species2":sim[:,1]})
print ggplot(simDF,aes(x="t",y="species1"))+geom_line()+geom_line(simDF,aes(x="t",y="species2"),color='red')+theme_classic()

#case2
times=range(0,100)
y0=[0.1,0.1]
params=(0.5,0.003,0.4,0.5,0.07,0.3)

sim=spint.odeint(func=coexistSim,y0=y0,t=times,args=params)
simDF=pandas.DataFrame({"t":times,"species1":sim[:,0],"species2":sim[:,1]})
print ggplot(simDF,aes(x="t",y="species1"))+geom_line()+geom_line(simDF,aes(x="t",y="species2"),color='green')+theme_classic()

#case3 - a12<a11; a21<a22
times=range(0,100)
y0=[0.1,0.1]
params=(0.5,0.1,0.0009,0.5,0.45,0.003)

sim=spint.odeint(func=coexistSim,y0=y0,t=times,args=params)
simDF=pandas.DataFrame({"t":times,"species1":sim[:,0],"species2":sim[:,1]})
print ggplot(simDF,aes(x="t",y="species1"))+geom_line()+geom_line(simDF,aes(x="t",y="species2"),color='blue')+theme_classic()



